// Copyright 2026 The semctl authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package commands

import (
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// skipCommands are auto-generated helper commands that add noise to a reference.
var skipCommands = map[string]bool{"help": true, "completion": true}

// RenderMarkdownDocs renders the full command tree rooted at root as a single
// markdown document: a title, the global flags, then one section per command
// (depth-first, alphabetically) with its description, usage, examples, and
// command-specific flags. The output is deterministic so it can be committed
// and regenerated without spurious diffs.
func RenderMarkdownDocs(root *cobra.Command) string {
	var b strings.Builder

	b.WriteString("# " + root.Name() + " command reference\n\n")
	b.WriteString("<!-- Generated by `go generate ./internal/commands/...`; do not edit by hand. -->\n\n")
	if short := strings.TrimSpace(root.Short); short != "" {
		b.WriteString(short + "\n\n")
	}

	if globals := root.PersistentFlags().FlagUsages(); strings.TrimSpace(globals) != "" {
		b.WriteString("## Global flags\n\n")
		b.WriteString("These flags are accepted by every command:\n\n")
		writeCodeBlock(&b, "", globals)
	}

	for _, c := range sortedChildren(root) {
		writeCommand(&b, c)
	}

	return b.String()
}

// writeCommand renders one command section and recurses into its subcommands.
func writeCommand(b *strings.Builder, cmd *cobra.Command) {
	b.WriteString("## " + cmd.CommandPath() + "\n\n")

	if short := strings.TrimSpace(cmd.Short); short != "" {
		b.WriteString(short + "\n\n")
	}
	if long := strings.TrimSpace(cmd.Long); long != "" && long != strings.TrimSpace(cmd.Short) {
		b.WriteString(long + "\n\n")
	}

	b.WriteString("Usage:\n\n")
	writeCodeBlock(b, "", cmd.UseLine())

	if aliases := cmd.Aliases; len(aliases) > 0 {
		b.WriteString("Aliases: " + strings.Join(aliases, ", ") + "\n\n")
	}

	if ex := strings.TrimSpace(cmd.Example); ex != "" {
		b.WriteString("Examples:\n\n")
		writeCodeBlock(b, "bash", dedent(cmd.Example))
	}

	if flags := cmd.LocalFlags().FlagUsages(); strings.TrimSpace(flags) != "" {
		b.WriteString("Flags:\n\n")
		writeCodeBlock(b, "", flags)
	}

	for _, c := range sortedChildren(cmd) {
		writeCommand(b, c)
	}
}

// sortedChildren returns the documentable subcommands of cmd, sorted by name so
// the rendered output is stable across runs.
func sortedChildren(cmd *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, c := range cmd.Commands() {
		if c.Hidden || !c.IsAvailableCommand() || skipCommands[c.Name()] {
			continue
		}
		out = append(out, c)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name() < out[j].Name() })
	return out
}

// writeCodeBlock writes a fenced code block with the given language tag.
func writeCodeBlock(b *strings.Builder, lang, body string) {
	b.WriteString("```" + lang + "\n")
	b.WriteString(strings.TrimRight(body, "\n"))
	b.WriteString("\n```\n\n")
}

// dedent removes a uniform two-space indent from cobra Example blocks so they
// render cleanly inside a fenced code block.
func dedent(s string) string {
	lines := strings.Split(s, "\n")
	for i, ln := range lines {
		lines[i] = strings.TrimPrefix(ln, "  ")
	}
	return strings.Join(lines, "\n")
}
